services:
  mysql:
    image: mysql:8.0
    container_name: mysql_book_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Praisejah_root
      MYSQL_DATABASE: library_db
      MYSQL_USER: Praisejah
      MYSQL_PASSWORD: password
      MYSQL_AUTH_PLUGIN: caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
